routes:
  /: 
    template: home

collections:
  /engineering-rules/:
    permalink: /engineering-rules/{slug}/
    filter: tag:[engineering-rules]
    template: engineering-rules-index
  /blogs/:
    permalink: /blogs/{slug}/
    filter: tag:-[engineering-rules]
    template: index

taxonomies:
  tag: /tags/{slug}/
  author: /authors/{slug}/
